export const transactions = [
  {
    id: "txn-1001",
    adTitle: "Maths Tuition - Pune",
    template: "Education - Featured",
    placement: "Home + Category Top Slot",
    durationDays: 3,
    baseAmount: 30,
    platformFee: 5,
    gst: 5.4,
    subtotal: 35,
    totalPaid: 40.4,
    paymentMethod: "UPI",
    paymentProvider: "Google Pay",
    paidOn: "2026-03-01",
    status: "Success",
    transactionRef: "UPI-AXIS-893472",
    billedTo: "Atharv Apugade",
    adId: "AD-EDU-22091",
    notes: "Priority placement enabled for 72 hours",
  },
  {
    id: "txn-1002",
    adTitle: "iPhone 14 Pro Sale",
    template: "Electronics - Premium",
    placement: "Search Boost + Category Banner",
    durationDays: 5,
    baseAmount: 90,
    platformFee: 10,
    gst: 18,
    subtotal: 100,
    totalPaid: 118,
    paymentMethod: "Card",
    paymentProvider: "Visa **** 4281",
    paidOn: "2026-02-15",
    status: "Success",
    transactionRef: "CARD-HDFC-112904",
    billedTo: "Atharv Apugade",
    adId: "AD-ELX-88107",
    notes: "Premium card with boosted CTR package",
  },
  {
    id: "txn-1003",
    adTitle: "Dog for Adoption",
    template: "Pets - Basic",
    placement: "Category Listing",
    durationDays: 2,
    baseAmount: 8,
    platformFee: 1,
    gst: 1,
    subtotal: 9,
    totalPaid: 10,
    paymentMethod: "UPI",
    paymentProvider: "PhonePe",
    paidOn: "2026-01-28",
    status: "Failed",
    transactionRef: "UPI-ICICI-552908",
    billedTo: "Atharv Apugade",
    adId: "AD-PET-44162",
    notes: "Payment failed first attempt due to bank timeout",
  },
  {
    id: "txn-1004",
    adTitle: "Gaming Chair - Ergonomic",
    template: "Furniture - Premium",
    placement: "Home Spotlight",
    durationDays: 7,
    baseAmount: 140,
    platformFee: 12,
    gst: 27.36,
    subtotal: 152,
    totalPaid: 179.36,
    paymentMethod: "Card",
    paymentProvider: "Mastercard **** 7719",
    paidOn: "2026-01-12",
    status: "Success",
    transactionRef: "CARD-SBI-884712",
    billedTo: "Atharv Apugade",
    adId: "AD-FUR-77801",
    notes: "Premium furniture promotion pack",
  },
  {
    id: "txn-1005",
    adTitle: "Scooter on Rent - Hinjewadi",
    template: "Vehicles - Basic",
    placement: "Category Listing",
    durationDays: 4,
    baseAmount: 32,
    platformFee: 3,
    gst: 6.3,
    subtotal: 35,
    totalPaid: 41.3,
    paymentMethod: "UPI",
    paymentProvider: "PhonePe",
    paidOn: "2025-12-22",
    status: "Failed",
    transactionRef: "UPI-KOTAK-992301",
    billedTo: "Atharv Apugade",
    adId: "AD-VEH-66210",
    notes: "UPI collect request expired before confirmation",
  },
];

export function getTransactionById(id) {
  return transactions.find((transaction) => transaction.id === id);
}
