# Frontend Dockerfile - Next.js standalone build using Debian-slim
FROM node:20-bullseye-slim AS builder

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Install build tools for native deps
RUN apt-get update \
	&& apt-get install -y --no-install-recommends python3 build-essential git curl ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci

# Copy sources and build
COPY . .
RUN npm run build

# Production image
FROM node:20-bullseye-slim

ENV NODE_ENV=production
ENV PORT=3000
WORKDIR /app

# Create non-root user
RUN groupadd -r app && useradd -r -g app -s /sbin/nologin app || true

# Copy the standalone package.json generated by Next and install production deps
COPY --from=builder /app/.next/standalone/package.json ./package.json
RUN apt-get update \
	&& apt-get install -y --no-install-recommends curl ca-certificates \
	&& rm -rf /var/lib/apt/lists/* \
	&& npm ci --only=production --no-audit --progress=false

# Copy standalone server and static assets
COPY --from=builder /app/.next/standalone .
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static

RUN chown -R app:app /app
USER app

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD curl -f http://localhost:3000/ || exit 1

CMD ["node", "server.js"]
